# Trigger builds on commits and merges to all branches, excluding specified branches
trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
    - README.md

# Trigger builds on PRs to branch
pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - README.md

# Execute on a schedule (measure drift from desired state)
schedules:
- cron: "0 */24 * * *"
  displayName: Run daily
  branches:
    include:
    - main
  always: true

# Trigger for agent build dependency
resources:
  pipelines:
  - pipeline: 'Agent Build'  
    source: ENV-P;REF-latest; pkr-agent_services
    trigger:    
      stages:
      - Build

extends:
  template: ./Shared/azure-pipelines.yml