jobs:
- deployment: ReDeploy
  continueOnError: false
  environment: '$(Environment)'
  strategy:
    runOnce:
      deploy:
        steps:

        # Checkout shared steps
        - checkout: 'tfpipeline-shared'
          displayName: 'Checkout shared Pipeline Steps'
          path: 's/pipeline/Shared/'

        # Run common steps
        - template: ./Steps/common.yml@tfpipeline-shared

        # Run steps
        - template: ./Steps/reapply.yml@tfpipeline-shared

        # Cleanup agent images
        - template: ./Steps/runnerimages/cleanup.yml@tfpipeline-shared
          parameters:
            imageResourceGroupName: $(ImageResourceGroupName_Linux)
        - template: ./Steps/runnerimages/cleanup.yml@tfpipeline-shared
          parameters:
            imageResourceGroupName: $(ImageResourceGroupName_Windows)