stages:
- stage: Apply
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Plan
  condition: and(not(failed()), not(canceled()), ne(dependencies.Plan.outputs['Evaluate.OPAVariable.AutoApproveShouldRun'], 'true'), eq(dependencies.Plan.outputs['Plan.Variable.ShouldRun'], 'true'))
  jobs:

  # Apply Jobs
  - template: ../Jobs/apply.yml

  # Cleanup Job
  - template: ../Jobs/cleanup_linux.yml
  - template: ../Jobs/cleanup_windows.yml